### ISSUE TITLE
Overview duplicate links

### ISSUE THREAD

**Issue by TinCan86** [XenitAB/xenitab.github.io#17]
Sometimes when generating docs, we get more then one overview. 

![Screenshot 2021-04-15 at 09 07 26](https://user-images.githubusercontent.com/14233283/114828308-06532900-9dca-11eb-9545-700c6fce3016.png)

**Comment by ulrikstrid** [comment]
The issue is that `SECURITY` and `CONTRIBUTING` is getting the wrong slug. `SECURITY` can be filtered out since we now have a generic for everything. `CONTRIBUTING` should have a special case like `CHANGELOG`.

**Comment by simongottschlag** [comment]
Solved by https://github.com/XenitAB/xenitab.github.io/pull/46
